### ISSUE TITLE
⭐Typing in 'auto' is redundant.

### ISSUE THREAD

**Issue by Reckadon** [glappy-py/zoom_bot#1]
### Typing in 'auto' is redundant and Auto checking should be done automatically.
![image](https://user-images.githubusercontent.com/69901221/104280596-2d9c1080-54d2-11eb-98fd-bfe719e2c406.png)
#### After that u can wait and ask the user if he wants to quit or do manually.
- [ ] Implement this.

**Comment by glappy-py** [comment]
Nice idea , it will be implemented in 3 hours
